# Imagen base de Python
FROM python:3.9

# Configurar el directorio de trabajo
WORKDIR /app

# Instalamos dependencias para Postgres y nc para el entrypoint.sh
RUN apt update && apt install -y netcat-openbsd gcc libpq-dev

# Copiar los archivos de requerimientos e instalar dependencias
COPY requirements.txt /app/requirements.txt 
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del backend
COPY . /app

RUN chmod +x /app/entrypoint.sh

EXPOSE 8000

ENTRYPOINT [ "/app/entrypoint.sh" ]

