# Imagen base de Node.js
FROM node:18.20.4-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de dependencias e instalarlas
COPY package.json package-lock.json ./

RUN npm install

# Copiar el resto del código fuente
COPY . .

CMD ["npm", "start"]